### ISSUE TITLE
Commit Log

### ISSUE THREAD

**Issue by corneezius** [sarahisnorm/ColmarAcademy#1]
Your commit log was the first thing I noticed about your repo and I'm extremely impressed by it.  One thing, make sure that your commits complete this sentence.."This commit will.....". Other than that awesome work. Making detailed commits might seem trivial to some developers, but when working with a team or collaborators, maintaining a detailed commit log is essential. Keep up the good work here!

**Comment by sarahisnorm** [comment]
Thank you and I will make use of the 'This commit will...' , that is very useful
