### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by corneezius** [sarahisnorm/ColmarAcademy#3]
Grade: Exceeds Expectations

Your page look amazing and your code is cleanly written :). Awesome job! My only challenge for you is to try and make your page look even better. Find and import cooler fonts , experiment with bootstrap, and browse for new ideas! Keep up the good work!

**Comment by sarahisnorm** [comment]
Thank you very much for this supportive and constructive feedback! It has filled me with lots of confidence.  I will take you up on your challenge.
